In [1]:
%matplotlib qt
from pathlib import Path
import pandas as pd
import numpy as np
import sys

sys.path.append(r'D:\Users\Csabi\dev\Cybathlon')

ONLY_KONTROLL_DATA = True

In [2]:
path = Path(r'D:\Users\Csabi\OneDrive - Pázmány Péter Katolikus Egyetem\1 Projects\Onkology\data')
file = path.joinpath('ibd_scratch.csv')

In [3]:
df_ = pd.read_csv(file, sep=';')
df_ = df_.fillna(0)
df_.replace(0, np.nan, inplace=True)
df_

,Látóterek,0h,4h,8h,12h,16h,20h,24h,28h,32h,...,52h,56h,60h,64h,68h,72h,cell size (um),type,cell line,investigation
0,1,458904.0,340173.0,238844.0,117803.0,41759.0,4972.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2953,kontroll,A2058,scratch
1,2,513838.0,420923.0,312834.0,211242.0,104502.0,64781.0,3221.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2953,kontroll,A2058,scratch
2,3,541644.0,440605.0,395327.0,327881.0,232424.0,157235.0,74166.0,29989.0,4026.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2953,kontroll,A2058,scratch
3,4,474364.0,386964.0,298746.0,227878.0,133790.0,82500.0,27930.0,6104.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2953,kontroll,A2058,scratch
4,37,505309.0,415280.0,309363.0,249418.0,153145.0,97358.0,38033.0,15524.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2953,kontroll,A2058,scratch
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,44,494827.0,419670.0,337017.0,288235.0,232044.0,195344.0,150472.0,126335.0,98649.0,...,4292.0,2041.0,NaN,NaN,NaN,NaN,6146,2 uM,JL Post,Ibidi
476,45,485367.0,392796.0,285407.0,226484.0,164450.0,124940.0,70441.0,41986.0,26276.0,...,NaN,NaN,NaN,NaN,NaN,NaN,6146,2 uM,JL Post,Ibidi
477,43,505138.0,419171.0,363928.0,311028.0,256530.0,208082.0,171747.0,135777.0,113006.0,...,50123.0,48663.0,44621.0,40750.0,43493.0,39080.0,6146,2 uM,JL Post,Ibidi
478,44,533532.0,455091.0,374403.0,329583.0,259795.0,213844.0,181416.0,145183.0,121642.0,...,58148.0,25630.0,8875.0,7015.0,8539.0,8551.0,6146,2 uM,JL Post,Ibidi
479,45,520998.0,440687.0,379665.0,330853.0,273212.0,232365.0,199789.0,170063.0,141364.0,...,NaN,NaN,NaN,NaN,NaN,NaN,6146,2 uM,JL Post,Ibidi

In [4]:
file = path.joinpath('cell_line_profile.csv')
df_prof = pd.read_csv(file, sep=';')
df_prof = df_prof.drop('ID / plate', axis=1)
gr = ['cell line', 'type']
df_prof = df_prof.groupby(gr).mean() * 2.18  # (um)
df_prof = df_prof.loc[df_[gr[0]].unique(),df_[gr[1]].unique(),:] 
df_prof

                           Area      Circ        AR     Round  Solidity
cell line type
A2058     kontroll  2953.229231  1.393590  5.878253  1.029094  1.964247
          1 uM      2895.178413  1.212703  6.976173  0.873557  1.881755
          2 uM      3645.282963  1.310624  6.554574  0.960169  1.952957
WM983B    kontroll  2127.580909  1.521244  4.232866  1.252179  1.966955
          1 uM      2402.052958  1.621152  4.305408  1.291481  2.050643
          2 uM      2258.971268  1.643413  4.236354  1.237626  2.040357
JR Pre    kontroll  3028.973750  1.610938  4.456574  1.225160  2.047674
          1 uM      3717.316765  1.655229  4.010110  1.327171  2.042468
          2 uM      3723.010606  1.694950  3.912968  1.335481  2.053494
JR Post   kontroll  2210.607200  1.597853  4.391828  1.273905  1.995369
          1 uM      2808.415278  1.619377  4.691118  1.199091  2.065641
          2 uM      2808.255238  1.614999  4.634299  1.214260  2.038404
JL Post   kontroll  6146.417627  1.210048  4.805939  1.178974  1.754050
          1 uM      5292.694390  1.342614  4.268121  1.262512  1.876900
          2 uM      4600.158356  1.420106  4.570594  1.265236  1.893912

In [5]:
if ONLY_KONTROLL_DATA:
    gr = ['cell line']
    df_prof = df_prof.loc[(slice(None), 'kontroll'),:]
    display(df_prof)

                           Area      Circ        AR     Round  Solidity
cell line type
A2058     kontroll  2953.229231  1.393590  5.878253  1.029094  1.964247
WM983B    kontroll  2127.580909  1.521244  4.232866  1.252179  1.966955
JR Pre    kontroll  3028.973750  1.610938  4.456574  1.225160  2.047674
JR Post   kontroll  2210.607200  1.597853  4.391828  1.273905  1.995369
JL Post   kontroll  6146.417627  1.210048  4.805939  1.178974  1.754050

In [6]:
df = pd.merge(df_, df_prof, on=gr, how='right')
profile = df[df_prof.columns]

In [7]:
labels = ['type', 'cell line', 'investigation'] 
x = df.drop(labels + ['cell size (um)', 'Látóterek'] + list(profile.columns), axis=1)
y_ = df[labels]
y_.drop_duplicates()

         type cell line investigation
0    kontroll     A2058       scratch
24       1 uM     A2058       scratch
45       2 uM     A2058       scratch
69   kontroll     A2058         Ibidi
81       1 uM     A2058         Ibidi
93       2 uM     A2058         Ibidi
103  kontroll    WM983B       scratch
122      1 uM    WM983B       scratch
142      2 uM    WM983B       scratch
162  kontroll    WM983B         Ibidi
174      1 uM    WM983B         Ibidi
186      2 uM    WM983B         Ibidi
198  kontroll    JR Pre       scratch
220      1 uM    JR Pre       scratch
242      2 uM    JR Pre       scratch
261  kontroll    JR Pre         Ibidi
273      1 uM    JR Pre         Ibidi
285      2 uM    JR Pre         Ibidi
297  kontroll   JR Post       scratch
318      1 uM   JR Post       scratch
338      2 uM   JR Post       scratch
360  kontroll   JR Post         Ibidi
372      1 uM   JR Post         Ibidi
384      2 uM   JR Post         Ibidi
396  kontroll   JL Post       scratch
411      1 uM   JL Post       scratch
425      2 uM   JL Post       scratch
444  kontroll   JL Post         Ibidi
456      1 uM   JL Post         Ibidi
468      2 uM   JL Post         Ibidi

In [8]:
x

,0h,4h,8h,12h,16h,20h,24h,28h,32h,36h,40h,44h,48h,52h,56h,60h,64h,68h,72h
0,458904.0,340173.0,238844.0,117803.0,41759.0,4972.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,513838.0,420923.0,312834.0,211242.0,104502.0,64781.0,3221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,541644.0,440605.0,395327.0,327881.0,232424.0,157235.0,74166.0,29989.0,4026.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,474364.0,386964.0,298746.0,227878.0,133790.0,82500.0,27930.0,6104.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,505309.0,415280.0,309363.0,249418.0,153145.0,97358.0,38033.0,15524.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,494827.0,419670.0,337017.0,288235.0,232044.0,195344.0,150472.0,126335.0,98649.0,56193.0,30560.0,22538.0,10595.0,4292.0,2041.0,NaN,NaN,NaN,NaN
476,485367.0,392796.0,285407.0,226484.0,164450.0,124940.0,70441.0,41986.0,26276.0,15282.0,7144.0,2056.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,505138.0,419171.0,363928.0,311028.0,256530.0,208082.0,171747.0,135777.0,113006.0,89780.0,84100.0,66004.0,57523.0,50123.0,48663.0,44621.0,40750.0,43493.0,39080.0
478,533532.0,455091.0,374403.0,329583.0,259795.0,213844.0,181416.0,145183.0,121642.0,94663.0,87312.0,69170.0,62839.0,58148.0,25630.0,8875.0,7015.0,8539.0,8551.0
479,520998.0,440687.0,379665.0,330853.0,273212.0,232365.0,199789.0,170063.0,141364.0,116507.0,105813.0,86923.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
f = x.copy()
dcols = x.columns

f['mean'] = x.mean(axis=1)
f['std'] = x.std(axis=1)
f['kurtosis'] = x.kurtosis(axis=1)
f['skew'] = x.skew(axis=1)

shrink = x.diff(axis=1) * -1
# display(shrink)
f['shrink mean'] = shrink.mean(axis=1)
f['shrink std'] = shrink.std(axis=1)
f['shrink kurtosis'] = shrink.kurtosis(axis=1)
f['shrink skew'] = shrink.skew(axis=1)

# normed with cell profile data
for tp in ['', 'shrink ']:
    for col in ['mean', 'std', 'kurtosis', 'skew']:
        for cell_par in profile.columns:
            f[f'{cell_par}_norm: {tp}{col}'] = f[f'{tp}{col}'] / profile[cell_par] * 2.18  # (um)
            # break;
        # f[f'ContArea_norm: {tp}{col}'] = f[f'{tp}{col}'] / df_['cell size (um)'] * 2.18  # (um)

def get_merged_state(df):
    m_list = []
    df = df.drop('0h', axis=1)
    cols = df.columns
    for ind in df.index:
        merged = False
        for i, el in enumerate(df.loc[ind]):
            if not (el >= 0):
                m_list.append(int(cols[i].strip('h')))
                merged = True
                break
        if not merged:
            m_list.append(np.nan)
    return m_list
        

f['merged'] = get_merged_state(shrink)
# f[f['merged'].isnull()]
f.drop(x.columns, axis=1)

,mean,std,kurtosis,skew,shrink mean,shrink std,shrink kurtosis,shrink skew,Area_norm: mean,Circ_norm: mean,...,Circ_norm: shrink kurtosis,AR_norm: shrink kurtosis,Round_norm: shrink kurtosis,Solidity_norm: shrink kurtosis,Area_norm: shrink skew,Circ_norm: shrink skew,AR_norm: shrink skew,Round_norm: shrink skew,Solidity_norm: shrink skew,merged
0,200409.166667,177775.186486,-1.352865,0.429179,90786.400000,35144.919488,0.201447,-1.055598,147.937037,313501.054903,...,0.315125,0.074708,0.426740,0.223574,-0.000779,-1.651277,-0.391477,-2.236144,-1.171544,24.0
1,233048.714286,190892.489152,-1.404991,0.343449,85102.833333,28082.838898,-0.482198,-1.073874,172.030736,364559.261373,...,-0.754304,-0.178827,-1.021472,-0.535162,-0.000793,-1.679866,-0.398255,-2.274860,-1.191828,28.0
2,244810.777778,192701.008352,-1.426149,0.182520,67202.250000,26646.813022,-1.214168,-0.272606,180.713197,382958.715719,...,-1.899329,-0.450284,-2.572054,-1.347532,-0.000201,-0.426439,-0.101098,-0.577481,-0.302549,36.0
3,204784.500000,171534.970814,-1.238272,0.412057,66894.285714,26003.223324,-0.155034,-0.779274,151.166799,320345.410570,...,-0.242521,-0.057496,-0.328420,-0.172063,-0.000575,-1.219023,-0.289001,-1.650790,-0.864870,32.0
4,222928.750000,178386.067127,-1.150165,0.427327,69969.285714,29022.746124,-0.501462,-0.374582,164.560431,348728.550972,...,-0.784439,-0.185971,-1.062280,-0.556542,-0.000277,-0.585961,-0.138917,-0.793503,-0.415726,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,164587.466667,159546.919953,-0.364446,0.832188,35199.000000,24949.906067,-0.493254,0.511422,58.375577,296517.772553,...,-0.888638,-0.223743,-0.912060,-0.613035,0.000181,0.921369,0.231984,0.945653,0.635615,60.0
476,153552.416667,162379.925032,-0.056403,1.009028,43937.363636,34622.490293,-0.624212,0.631414,54.461686,276637.228109,...,-1.124569,-0.283146,-1.154209,-0.775794,0.000224,1.137544,0.286413,1.167526,0.784745,48.0
477,160449.684211,144428.167417,0.397985,1.213029,25892.111111,25099.151108,0.048716,0.876298,56.907996,289063.219287,...,0.087766,0.022098,0.090079,0.060546,0.000311,1.578722,0.397493,1.620332,1.089096,68.0
478,160275.315789,160577.179610,0.252858,1.101777,29165.611111,26322.081486,-0.317165,0.790848,56.846152,288749.080325,...,-0.571399,-0.143868,-0.586459,-0.394185,0.000280,1.424778,0.358733,1.462331,0.982896,68.0
479,249853.250000,141395.135728,-0.605319,0.695227,39461.363636,20677.163869,-0.103143,0.648327,88.617487,450131.049803,...,-0.185821,-0.046786,-0.190719,-0.128190,0.000230,1.168015,0.294085,1.198800,0.805766,48.0

In [29]:
no_profile_mask = ['_norm:' not in  c for c in f.columns]

Index(['0h', '4h', '8h', '12h', '16h', '20h', '24h', '28h', '32h', '36h',
       '40h', '44h', '48h', '52h', '56h', '60h', '64h', '68h', '72h', 'mean',
       'std', 'kurtosis', 'skew', 'shrink mean', 'shrink std',
       'shrink kurtosis', 'shrink skew', 'merged'],
      dtype='object')

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedShuffleSplit

# X = x
# X = f.loc[:, no_profile_mask]
X = f
# X = f.drop(x.columns, axis=1)
X = X.fillna(-1)

VERBOSE = False

REPEAT_CV = 10
selection = 15  # first n feature

# cv = StratifiedKFold(n_splits=5)
cv = StratifiedShuffleSplit(n_splits=5)
pipe = RandomForestClassifier(n_estimators=500, n_jobs=-2)
# pipe = make_pipeline(
#         # PCA(n_components=.97),
#         StandardScaler(),
#         RandomForestClassifier(n_estimators=500, n_jobs=-2)
# )
# pipe = get_ensemble_clf('voting', 'hard')

# print(X.isnull().values.any())
# with pd.option_context('display.max_rows', None):
#     display(X)
X

,0h,4h,8h,12h,16h,20h,24h,28h,32h,36h,...,72h,mean,std,kurtosis,skew,shrink mean,shrink std,shrink kurtosis,shrink skew,merged
0,458904.0,340173.0,238844.0,117803.0,41759.0,4972.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,200409.166667,177775.186486,-1.352865,0.429179,90786.400000,35144.919488,0.201447,-1.055598,24.0
1,513838.0,420923.0,312834.0,211242.0,104502.0,64781.0,3221.0,-1.0,-1.0,-1.0,...,-1.0,233048.714286,190892.489152,-1.404991,0.343449,85102.833333,28082.838898,-0.482198,-1.073874,28.0
2,541644.0,440605.0,395327.0,327881.0,232424.0,157235.0,74166.0,29989.0,4026.0,-1.0,...,-1.0,244810.777778,192701.008352,-1.426149,0.182520,67202.250000,26646.813022,-1.214168,-0.272606,36.0
3,474364.0,386964.0,298746.0,227878.0,133790.0,82500.0,27930.0,6104.0,-1.0,-1.0,...,-1.0,204784.500000,171534.970814,-1.238272,0.412057,66894.285714,26003.223324,-0.155034,-0.779274,32.0
4,505309.0,415280.0,309363.0,249418.0,153145.0,97358.0,38033.0,15524.0,-1.0,-1.0,...,-1.0,222928.750000,178386.067127,-1.150165,0.427327,69969.285714,29022.746124,-0.501462,-0.374582,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,494827.0,419670.0,337017.0,288235.0,232044.0,195344.0,150472.0,126335.0,98649.0,56193.0,...,-1.0,164587.466667,159546.919953,-0.364446,0.832188,35199.000000,24949.906067,-0.493254,0.511422,60.0
476,485367.0,392796.0,285407.0,226484.0,164450.0,124940.0,70441.0,41986.0,26276.0,15282.0,...,-1.0,153552.416667,162379.925032,-0.056403,1.009028,43937.363636,34622.490293,-0.624212,0.631414,48.0
477,505138.0,419171.0,363928.0,311028.0,256530.0,208082.0,171747.0,135777.0,113006.0,89780.0,...,39080.0,160449.684211,144428.167417,0.397985,1.213029,25892.111111,25099.151108,0.048716,0.876298,68.0
478,533532.0,455091.0,374403.0,329583.0,259795.0,213844.0,181416.0,145183.0,121642.0,94663.0,...,8551.0,160275.315789,160577.179610,0.252858,1.101777,29165.611111,26322.081486,-0.317165,0.790848,68.0
479,520998.0,440687.0,379665.0,330853.0,273212.0,232365.0,199789.0,170063.0,141364.0,116507.0,...,-1.0,249853.250000,141395.135728,-0.605319,0.695227,39461.363636,20677.163869,-0.103143,0.648327,48.0

In [26]:
from utils import make_cv, get_importance

ver=VERBOSE
print(f'Investigate poison: {y_["type"].unique()}\n')

for method in y_['investigation'].unique():
    met_ind = y_['investigation'] == method
    mx, my = X.loc[met_ind], y_.loc[met_ind]
    imp = get_importance(mx, my, sort=True)
    most_imp = imp[:selection]
    feat = most_imp.index

    print(f'Method: {method} - Selected {len(feat)} features:\n{list(feat)}\n')
    data = mx[feat]

    for cell_line in my['cell line'].unique():
        if ver:
            print(f'\n======================================================')
        print(f'Investigation: {cell_line}')

        ind = my['cell line'] == cell_line

        make_cv(pipe, cv, data.loc[ind].values, my.loc[ind]['type'].values, repeat=REPEAT_CV, verbose=ver)
    # print()

    print(f'\n{method} - Controlls: {my["cell line"].unique()}\n')
    ind = my['type'] == 'kontroll'
    make_cv(pipe, cv, data.loc[ind].values, my.loc[ind]['cell line'].values, repeat=REPEAT_CV, verbose=ver)

Investigate poison: ['kontroll' '1 uM' '2 uM']

Method: scratch - Selected 15 features:
['shrink mean', 'shrink std', 'shrink skew', '16h', 'kurtosis', '48h', '12h', '8h', 'skew', '20h', '28h', 'merged', '24h', '32h', '36h']

Investigation: A2058
0.7114 +/- 0.0453 conf(0.95),	 0.1578 std
Investigation: WM983B
0.6867 +/- 0.0475 conf(0.95),	 0.1655 std
Investigation: JR Pre
0.6057 +/- 0.0482 conf(0.95),	 0.1680 std
Investigation: JR Post
0.8143 +/- 0.0459 conf(0.95),	 0.1597 std
Investigation: JL Post
0.8040 +/- 0.0520 conf(0.95),	 0.1811 std

scratch - Controlls: ['A2058' 'WM983B' 'JR Pre' 'JR Post' 'JL Post']

0.8545 +/- 0.0295 conf(0.95),	 0.1029 std
Method: Ibidi - Selected 15 features:
['skew', '4h', '20h', '16h', '12h', '8h', '0h', '36h', '24h', '32h', '28h', 'shrink mean', '40h', 'mean', 'std']

Investigation: A2058
0.8050 +/- 0.0579 conf(0.95),	 0.2018 std
Investigation: WM983B
0.5850 +/- 0.0667 conf(0.95),	 0.2324 std
Investigation: JR Pre
0.6100 +/- 0.0577 conf(0.95),	 0.2010 std
Investigation: JR Post
0.7600 +/- 0.0608 conf(0.95),	 0.2119 std
Investigation: JL Post
0.9550 +/- 0.0342 conf(0.95),	 0.1193 std

Ibidi - Controlls: ['A2058' 'WM983B' 'JR Pre' 'JR Post' 'JL Post']

0.7733 +/- 0.0466 conf(0.95),	 0.1625 std

In [27]:
ver=VERBOSE
print(f'Investigate Controlls: {y_["cell line"].unique()} - all features')
for method in y_['investigation'].unique():
    if ver:
        print(f'\n======================================================')
    print(f'Investigation: {method}')

    ind = (y_['investigation'] == method) & (y_['type'] == 'kontroll')
    
    make_cv(pipe, cv, X.loc[ind].values, y_.loc[ind]['cell line'].values, repeat=REPEAT_CV, verbose=ver)

Investigate Controlls: ['A2058' 'WM983B' 'JR Pre' 'JR Post' 'JL Post'] - all features
Investigation: scratch
0.8418 +/- 0.0275 conf(0.95),	 0.0959 std
Investigation: Ibidi
0.8033 +/- 0.0494 conf(0.95),	 0.1722 std

In [28]:
# ver=VERBOSE
#
# # print(f'Investigation for top {selection} feature by method.')
#
# # print(f'Investigate poison: {y["type"].unique()}')
# for method in y['investigation'].unique():
#     feat = get_importance(X, y, plot=True)[:selection].index
#     print(f'\n{method} - Selected features:\n{list(feat)}\n')
#     # data = X[feat]
#
#     # for cell_line in y[y['investigation']==method]['cell line'].unique():
#     #     if ver:
#     #         print(f'\n======================================================')
#     #     print(f'Investigation: {method}-{cell_line}')
#
#     #     ind = (y['investigation'] == method) & (y['cell line'] == cell_line)
#
#     #     make_cv(pipe, cv, data[ind].values, y[ind]['type'].values, verbose=ver)